services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: myats-backend

    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: myats-frontend

    ports:
      - "5173:5173"

    environment:
      VITE_API_URL: http://localhost:8000

    depends_on:
      - backend
